// This file is auto-generated by @tanstack/router-vite-plugin. The plugin
// rewrites it on every dev server start / build. The committed copy is a
// minimal placeholder so `tsc --noEmit` passes before `vite dev` runs once.

import { rootRouteWithContext } from '@tanstack/react-router';

export const routeTree = rootRouteWithContext()({
  component: () => null,
});
