/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingRouteImport } from './routes/waiting'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as AllRouteImport } from './routes/all'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as AreasIndexRouteImport } from './routes/areas/index'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'
import { Route as SettingsTodosRouteImport } from './routes/settings/todos'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as PeopleIdRouteImport } from './routes/people/$id'
import { Route as AreasIdRouteImport } from './routes/areas/$id'
import { Route as SettingsPlatformApprovalsRouteImport } from './routes/settings/platform.approvals'

const WaitingRoute = WaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRoute = AllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTodosRoute = SettingsTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIdRoute = AreasIdRouteImport.update({
  id: '/areas/$id',
  path: '/areas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPlatformApprovalsRoute =
  SettingsPlatformApprovalsRouteImport.update({
    id: '/platform/approvals',
    path: '/platform/approvals',
    getParentRoute: () => SettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/upcoming': typeof UpcomingRoute
  '/waiting': typeof WaitingRoute
  '/areas/$id': typeof AreasIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/todos': typeof SettingsTodosRoute
  '/tasks/$id': typeof TasksIdRoute
  '/areas/': typeof AreasIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/platform/approvals': typeof SettingsPlatformApprovalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/upcoming': typeof UpcomingRoute
  '/waiting': typeof WaitingRoute
  '/areas/$id': typeof AreasIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/todos': typeof SettingsTodosRoute
  '/tasks/$id': typeof TasksIdRoute
  '/areas': typeof AreasIndexRoute
  '/people': typeof PeopleIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings/platform/approvals': typeof SettingsPlatformApprovalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/upcoming': typeof UpcomingRoute
  '/waiting': typeof WaitingRoute
  '/areas/$id': typeof AreasIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/todos': typeof SettingsTodosRoute
  '/tasks/$id': typeof TasksIdRoute
  '/areas/': typeof AreasIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/platform/approvals': typeof SettingsPlatformApprovalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all'
    | '/inbox'
    | '/login'
    | '/review'
    | '/settings'
    | '/signup'
    | '/upcoming'
    | '/waiting'
    | '/areas/$id'
    | '/people/$id'
    | '/projects/$id'
    | '/settings/profile'
    | '/settings/todos'
    | '/tasks/$id'
    | '/areas/'
    | '/people/'
    | '/projects/'
    | '/settings/platform/approvals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all'
    | '/inbox'
    | '/login'
    | '/review'
    | '/settings'
    | '/signup'
    | '/upcoming'
    | '/waiting'
    | '/areas/$id'
    | '/people/$id'
    | '/projects/$id'
    | '/settings/profile'
    | '/settings/todos'
    | '/tasks/$id'
    | '/areas'
    | '/people'
    | '/projects'
    | '/settings/platform/approvals'
  id:
    | '__root__'
    | '/'
    | '/all'
    | '/inbox'
    | '/login'
    | '/review'
    | '/settings'
    | '/signup'
    | '/upcoming'
    | '/waiting'
    | '/areas/$id'
    | '/people/$id'
    | '/projects/$id'
    | '/settings/profile'
    | '/settings/todos'
    | '/tasks/$id'
    | '/areas/'
    | '/people/'
    | '/projects/'
    | '/settings/platform/approvals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllRoute: typeof AllRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  UpcomingRoute: typeof UpcomingRoute
  WaitingRoute: typeof WaitingRoute
  AreasIdRoute: typeof AreasIdRoute
  PeopleIdRoute: typeof PeopleIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  TasksIdRoute: typeof TasksIdRoute
  AreasIndexRoute: typeof AreasIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting': {
      id: '/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof WaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/todos': {
      id: '/settings/todos'
      path: '/todos'
      fullPath: '/settings/todos'
      preLoaderRoute: typeof SettingsTodosRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$id': {
      id: '/areas/$id'
      path: '/areas/$id'
      fullPath: '/areas/$id'
      preLoaderRoute: typeof AreasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/platform/approvals': {
      id: '/settings/platform/approvals'
      path: '/platform/approvals'
      fullPath: '/settings/platform/approvals'
      preLoaderRoute: typeof SettingsPlatformApprovalsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsTodosRoute: typeof SettingsTodosRoute
  SettingsPlatformApprovalsRoute: typeof SettingsPlatformApprovalsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsTodosRoute: SettingsTodosRoute,
  SettingsPlatformApprovalsRoute: SettingsPlatformApprovalsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllRoute: AllRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  UpcomingRoute: UpcomingRoute,
  WaitingRoute: WaitingRoute,
  AreasIdRoute: AreasIdRoute,
  PeopleIdRoute: PeopleIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  TasksIdRoute: TasksIdRoute,
  AreasIndexRoute: AreasIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
